# -*- coding: utf-8 -*-
"""Food Procurement Analytics .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sl0NCAR-0kF5GZfv0Hjk7XRVpcQdJ1zY
"""

import pandas as pd

df = pd.read_csv("/content/Good_Food_Purchasing_Data.csv")

print(df.shape)
df.head()

print(df.columns)

df.isnull().sum().sort_values(ascending=False)

df.describe()

top_vendors = (
    df.groupby('Vendor')['Total Cost']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_vendors)

top_groups = (
    df.groupby('Food Product Group')['Total Cost']
    .sum()
    .sort_values(ascending=False)
)

print(top_groups)

agency_spend = (
    df.groupby('Agency')['Total Cost']
    .sum()
    .sort_values(ascending=False)
)

print(agency_spend)

import matplotlib.pyplot as plt

top_vendors.plot(kind='bar')
plt.title("Top Vendors by Spend")
plt.ylabel("Total Cost")
plt.show()

top_groups.head(10).plot(kind='bar')
plt.title("Spend by Product Group")
plt.ylabel("Total Cost")
plt.show()

df.to_csv(
    "food_procurement_cleaned.csv",
    index=False
)

from google.colab import files

files.download("food_procurement_cleaned.csv")